"""
Default anchor labels for D₄ and E₈ lattices.

Anchors are canonical concepts that define the semantic axes of the lattice.
Each lattice needs exactly as many anchors as it has cells (vertices).
"""

# ---------------------------------------------------------------------------
# D₄ — 24 broad knowledge domains
# ---------------------------------------------------------------------------
D4_ANCHORS: list[str] = [
    "mathematics and logic",
    "physics and cosmology",
    "chemistry and materials",
    "biology and genetics",
    "medicine and health",
    "computer science and programming",
    "artificial intelligence and machine learning",
    "engineering and construction",
    "art and visual design",
    "music and sound",
    "literature and writing",
    "history and archaeology",
    "philosophy and ethics",
    "psychology and cognition",
    "economics and finance",
    "law and governance",
    "politics and society",
    "education and learning",
    "language and linguistics",
    "food and nutrition",
    "sports and fitness",
    "travel and geography",
    "nature and ecology",
    "space and astronomy",
]

assert len(D4_ANCHORS) == 24


# ---------------------------------------------------------------------------
# E₈ — 240 fine-grained sub-categories (10 per D₄ domain)
# ---------------------------------------------------------------------------
E8_ANCHORS: list[str] = [
    # Mathematics (10)
    "algebra and abstract structures",
    "calculus and mathematical analysis",
    "geometry and topology",
    "number theory and primes",
    "probability and statistics",
    "combinatorics and graph theory",
    "logic and set theory",
    "numerical methods and computation",
    "differential equations",
    "linear algebra and matrices",
    # Physics (10)
    "classical mechanics and dynamics",
    "quantum mechanics and particles",
    "electromagnetism and optics",
    "thermodynamics and entropy",
    "general relativity and gravity",
    "condensed matter physics",
    "nuclear physics and radiation",
    "fluid dynamics",
    "astrophysics and stellar physics",
    "plasma physics",
    # Chemistry (10)
    "organic chemistry",
    "inorganic chemistry",
    "physical chemistry",
    "biochemistry",
    "analytical chemistry",
    "polymer chemistry",
    "electrochemistry",
    "photochemistry",
    "materials science",
    "nanotechnology",
    # Biology (10)
    "molecular biology and DNA",
    "cell biology and organelles",
    "genetics and heredity",
    "evolutionary biology",
    "microbiology and viruses",
    "botany and plant science",
    "zoology and animal science",
    "marine biology and oceanography",
    "neuroscience and brain",
    "developmental biology and embryology",
    # Medicine (10)
    "anatomy and physiology",
    "pharmacology and drugs",
    "surgery and procedures",
    "immunology and vaccines",
    "oncology and cancer",
    "cardiology and heart",
    "psychiatry and mental health",
    "infectious diseases and epidemiology",
    "radiology and imaging",
    "veterinary medicine and animal health",
    # Computer Science (10)
    "algorithms and data structures",
    "operating systems and kernels",
    "databases and storage",
    "networking and protocols",
    "cybersecurity and cryptography",
    "web development and frontend",
    "mobile development and apps",
    "distributed systems and cloud",
    "compilers and programming languages",
    "software engineering and architecture",
    # AI and ML (10)
    "deep learning and neural networks",
    "natural language processing",
    "computer vision and image recognition",
    "reinforcement learning and agents",
    "generative AI and large language models",
    "robotics and autonomous systems",
    "recommendation systems",
    "speech recognition and synthesis",
    "knowledge graphs and reasoning",
    "AI ethics and alignment",
    # Engineering (10)
    "mechanical engineering and design",
    "electrical engineering and circuits",
    "civil engineering and infrastructure",
    "chemical engineering and processes",
    "aerospace engineering and flight",
    "automotive engineering and vehicles",
    "biomedical engineering",
    "environmental engineering",
    "telecommunications and signals",
    "industrial engineering and manufacturing",
    # Art and Design (10)
    "painting and drawing",
    "sculpture and installation",
    "photography and videography",
    "graphic design and branding",
    "architecture and urban planning",
    "fashion and textile design",
    "digital art and 3D modeling",
    "animation and motion graphics",
    "interior design and decoration",
    "art history and critique",
    # Music (10)
    "classical music and orchestra",
    "rock and pop music",
    "jazz and blues",
    "electronic music and production",
    "hip hop and rap",
    "folk and traditional music",
    "music theory and composition",
    "sound engineering and mixing",
    "musical instruments and performance",
    "opera and vocal arts",
    # Literature (10)
    "fiction and novels",
    "poetry and verse",
    "drama and theater",
    "non-fiction and essays",
    "journalism and reporting",
    "children's literature",
    "science fiction and fantasy",
    "mystery and thriller",
    "biography and memoir",
    "literary criticism and theory",
    # History (10)
    "ancient civilizations",
    "medieval history and feudalism",
    "renaissance and enlightenment",
    "modern history and world wars",
    "cold war and geopolitics",
    "colonial history and empires",
    "economic history and trade",
    "military history and strategy",
    "social movements and revolutions",
    "cultural heritage and preservation",
    # Philosophy (10)
    "metaphysics and ontology",
    "epistemology and knowledge",
    "ethics and moral philosophy",
    "political philosophy",
    "philosophy of mind and consciousness",
    "philosophy of science",
    "existentialism and phenomenology",
    "logic and argumentation",
    "aesthetics and beauty",
    "Eastern philosophy and wisdom",
    # Psychology (10)
    "cognitive psychology and perception",
    "behavioral psychology",
    "clinical psychology and therapy",
    "social psychology and group dynamics",
    "developmental psychology and childhood",
    "personality and individual differences",
    "positive psychology and wellbeing",
    "neuropsychology and brain injury",
    "organizational psychology and work",
    "psychology of motivation and emotion",
    # Economics (10)
    "microeconomics and markets",
    "macroeconomics and fiscal policy",
    "international trade and globalization",
    "financial markets and investing",
    "banking and monetary policy",
    "behavioral economics",
    "labor economics and employment",
    "public economics and taxation",
    "economic development and poverty",
    "cryptocurrency and digital finance",
    # Law (10)
    "constitutional law and rights",
    "criminal law and justice",
    "civil law and contracts",
    "international law and treaties",
    "intellectual property and patents",
    "corporate law and regulation",
    "environmental law and policy",
    "human rights and advocacy",
    "family law and domestic issues",
    "legal philosophy and jurisprudence",
    # Politics (10)
    "democracy and elections",
    "authoritarianism and dictatorship",
    "international relations and diplomacy",
    "political parties and ideology",
    "public policy and governance",
    "warfare and conflict resolution",
    "media and propaganda",
    "civil liberties and freedom",
    "immigration and borders",
    "political economy and inequality",
    # Education (10)
    "pedagogy and teaching methods",
    "curriculum design and assessment",
    "higher education and universities",
    "early childhood education",
    "special education and inclusion",
    "online learning and MOOCs",
    "educational technology and tools",
    "literacy and reading",
    "STEM education",
    "vocational training and skills",
    # Language (10)
    "syntax and grammar",
    "semantics and meaning",
    "phonetics and pronunciation",
    "translation and interpretation",
    "sociolinguistics and dialect",
    "second language acquisition",
    "computational linguistics",
    "sign language and nonverbal",
    "etymology and word origins",
    "rhetoric and persuasion",
    # Food (10)
    "cooking techniques and recipes",
    "baking and pastry",
    "nutrition and dietetics",
    "food science and preservation",
    "wine and beverages",
    "restaurant and hospitality",
    "food culture and traditions",
    "organic and sustainable food",
    "food safety and regulation",
    "fermentation and probiotics",
    # Sports (10)
    "football and soccer",
    "basketball and team sports",
    "tennis and racket sports",
    "swimming and water sports",
    "athletics and track events",
    "martial arts and combat sports",
    "extreme sports and adventure",
    "fitness and bodybuilding",
    "sports medicine and injury",
    "esports and gaming",
    # Travel (10)
    "tourism and destinations",
    "cultural travel and heritage sites",
    "adventure and outdoor travel",
    "transportation and logistics",
    "hotels and accommodation",
    "travel photography and blogging",
    "ecotourism and conservation",
    "cruise and maritime travel",
    "backpacking and budget travel",
    "travel safety and health",
    # Nature (10)
    "climate and weather",
    "geology and earth science",
    "forests and ecosystems",
    "wildlife and conservation",
    "rivers and water resources",
    "mountains and landforms",
    "deserts and arid environments",
    "biodiversity and extinction",
    "natural disasters and resilience",
    "agriculture and farming",
    # Space (10)
    "solar system and planets",
    "stars and galaxies",
    "black holes and dark matter",
    "space exploration and missions",
    "satellite technology and GPS",
    "astrobiology and extraterrestrial life",
    "cosmology and Big Bang",
    "space engineering and rockets",
    "space policy and governance",
    "telescopes and observatories",
]

assert len(E8_ANCHORS) == 240
